### ISSUE TITLE
rtl bug in last version

### ISSUE THREAD

**Issue by ali-hardan** [annulen/webkit#768] opened 2018-08-17 09:16 UTC
Hello. I see one rtl bug in last version of QtWebKit, which (I think) wasn't exists in 5.7 version.

I'm using `libqt5webkit5 5.212.0~alpha2-15` on `debian sid i386`.

```
<p dir="rtl">

<span style="color:#FF0000">آزمایش</span>سلام عرض می‌کنم محضر کسی که می‌خواند.

<br>

</p>
```

when I render this using QtWebKit, the output is: 
![QtWebKit output](https://user-images.githubusercontent.com/4679877/44258157-69f4b500-a223-11e8-99ec-ab7be47fb74e.png)

But when I render using chromium, output is OK and it:
![Chromium output](https://user-images.githubusercontent.com/4679877/44258249-a58f7f00-a223-11e8-9ac5-8b5268982689.png)

**It's high important bug. With this bug, normal use of RTL texts will not possible**

url in qt bug reports:

https://bugreports.qt.io/browse/QTBUG-70026

**Comment by ali-hardan** [comment] 2018-08-17 17:28
I have tested on qt4 webkit, there are not exists this bug.

**Comment by ali-hardan** [comment] 2018-08-17 17:32
It is unlikely to be this problem from Webkit. Webkit always supported rtl very good.

**Comment by annulen** [comment] 2018-09-04 11:38
Duplicate of #722

**Closed by annulen** 2018-09-04 11:38 UTC
