### ISSUE TITLE
QtWebKit JavaScriptCore doesn't work on musl libc

### ISSUE THREAD

**Issue by Ronsor** [annulen/webkit#779] opened 2018-10-27 23:34 UTC
Using musl libc on Linux, JavaScript doesn't work.

```
Error compiling builtin:
Fatal error compiling builtin function 'apply':
```

the backtrace:

```
#0  0x099dd8d5 in WTFCrash ()
#1  0x096658f0 in JSC::createExecutableInternal(JSC::VM&, JSC::SourceCode const&, JSC::Identifier const&, JSC::ConstructorKind, JSC::ConstructAbility) ()
#2  0x096683e3 in JSC::BuiltinExecutables::functionPrototypeApplyCodeExecutable() ()
#3  0x0987ba48 in JSC::functionPrototypeApplyCodeGenerator(JSC::VM&) ()
#4  0x098f870a in JSC::FunctionPrototype::addFunctionProperties(JSC::ExecState*, JSC::JSGlobalObject*, JSC::JSFunction**, JSC::JSFunction**, JSC::JSFunction**) ()
#5  0x0979533c in JSC::JSGlobalObject::init(JSC::VM&) ()
```

Including any `<script></script>` tags on a page causes a crash.

**Comment by annulen** [comment] 2018-10-27 23:41
Duplicate of #708

**Closed by annulen** 2018-10-27 23:41 UTC
