### ISSUE TITLE
windows: static build with static runtime - is it possbile?

### ISSUE THREAD

**Issue by muffmolch** [annulen/webkit#116] opened 2016-06-20 12:07 UTC
Hi
One of the biggest disadvantages of QtWebKit and also QtWebengine is the missing support of having a static libraray th at is linked to static runtime within windows.

Is this possible here?

**Comment by annulen** [comment] 2016-06-20 12:08
I think yes, it will just require a few changes in build system

**Comment by muffmolch** [comment] 2016-06-20 12:12
Ok. Would be great! I really would like to test it.

**Comment by Vitallium** [comment] 2016-06-26 11:53
More information: looks like WebKit works fine with static Qt. But the problem is that we have to link other static libraries that Qt needs.

List of libraries from Qt (not completed):
* pcre
* qwindows (from platform)
* zlib
* freetype (not sure about this)

The same applies to Linux also.

**Comment by Vitallium** [comment] 2016-06-26 12:01
Upstream issue: https://bugreports.qt.io/browse/QTBUG-38913

**Comment by annulen** [comment] 2016-06-26 21:16
I think it should not be done in `WEBKIT_FRAMEWORK` macro, but via `target_link_libraries(Qt5::Gui INTERFACE ...)` and so on, the same way as it should have been done in Qt5 cmake files. Also we should ask @steveire if there is a chance to get QTBUG-38913 fixed.

**Comment by annulen** [comment] 2016-06-29 12:53
I think we should extract `QMAKE_PRL_LIBS` values from Qt's prl files similarly to what is done in https://codereview.qt-project.org/#/c/33193, and add them to respective library lists

**Comment by annulen** [comment] 2016-06-29 13:24
There is even more up-to-date Qt patch:

https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-qt5/0039-qt-5.4.0-Make-it-possible-to-use-static-builds-of-Qt-with-CMa.patch

**Comment by annulen** [comment] 2016-07-15 11:11
Related: #172

**Comment by Vitallium** [comment] 2016-09-30 19:24
All needed patches have been landed to `master`. Closed.

**Closed by Vitallium** 2016-09-30 19:24 UTC
Labels: junior job, windows
