### ISSUE TITLE
HTTP2 does not work

### ISSUE THREAD

**Issue by ajankov** [annulen/webkit#549] opened 2017-05-22 15:00 UTC
QtWebkit does not seem to support HTTP2 even if Qt 5.8 claims to support HTTP2. I have tested with this page : https://http2.akamai.com/demo 

Is there any option I can set to enable HTTP2 support? Thanks.

**Comment by annulen** [comment] 2017-05-22 15:14
It looks like the only way (without QtWebKit modification) is to make a subclass of QNAM, and in createRequest set `QNetworkRequest::HTTP2AllowedAttribute` for each QNetworkRequest

**Comment by ajankov** [comment] 2017-05-23 14:50
Thank you for this information and for the hard work to update the qtwebkit !

The HTTP2AllowedAttribute works well when accessing HTTP2 websites but it will crash for normal HTTP if HTTP is enabled.  Is there any option to automatically fallback to HTTP if HTTP2 is not supported by server (a kind of negociation between qtwebkit and the web server).

Is there are any new update similar to TP5 available for testing? Maybe an early alpha version? I just need the source not the prebuilt binaries. Thanks.

**Comment by annulen** [comment] 2017-05-23 14:52
Coming really soon, need to finish performance testing and add security patches

**Comment by ajankov** [comment] 2017-05-23 15:01
Thanks!

Any idea about the HTTP2 protocol handshaking between qtwebkit and web server? I think it should use HTTP instead of HTTP2 if HTTP2 is not available on server instead of throwing an error.

**Comment by annulen** [comment] 2017-05-23 15:08
Could you post backtrace from crash? If crash is inside Qt Network, it should be reported to bugreports.qt.io

**Comment by ajankov** [comment] 2017-05-23 15:11
It's not a crash. The page load returns with an error message saying that the protocol is broken.

**Comment by annulen** [comment] 2017-05-23 15:14
Does it reproduce in minimal application using QNAM?

**Comment by ajankov** [comment] 2017-05-23 17:47
It is reproducible only in a browser based on qtwebkit

**Comment by The-Compiler** [comment] 2017-05-26 12:33
I just tried as well, and I get `stream 1 finished with error: "invalid frame size"`.

**Comment by The-Compiler** [comment] 2017-06-13 15:57
Also see [QTBUG-61397](https://bugreports.qt.io/browse/QTBUG-61397).

**Comment by annulen** [comment] 2017-06-13 16:02
So, does it work if you set HTTP2AllowedAttribute for HTTPS reqests only?

**Comment by annulen** [comment] 2017-06-30 13:37
Fixed in 8b6714c930765f120d310c6fa07cd766bea8fbb9

**Comment by annulen** [comment] 2017-11-10 15:18
In https://bugreports.qt.io/browse/QTBUG-64359 Timur found that HTTP/2 implementation in QtNetwork does not handle reply with more than one Set-Cookie header correctly - only last header takes effect. It seems like we have to disable HTTP/2 support in QtWebKit until this bug is fixed (Qt 5.10.0 if all goes well).

Application that use QtWebKit still can enable HTTP/2 by setting `HTTP2AllowedAttribute`, if they want to use black list of domains that are broken with HTTP/2 (or white list where HTTP/2 works), e.g. I didn't see any reports about YouTube or Google (which surely use HTTP/2 if it's enabled)

**Comment by annulen** [comment] 2017-11-17 10:46
Fix was merged and is coming in Qt 5.10.0 RC (and 5.9.4)

**Comment by annulen** [comment] 2017-12-22 07:45
Fixed in deefab44104f99921ab16e56451e8ad84208a757

**Comment by annulen** [comment] 2018-01-18 15:33
Seems like it's not fine yet.

https://codereview.qt-project.org/#/c/212483/ - requests hang froever instead of HostNotFoundError, missed 5.10.0 deadline

https://bugreports.qt.io/browse/QTBUG-65849 - just stumbled upon

**Comment by annulen** [comment] 2018-01-23 00:02
HTTP/2 will be enabled by default for Qt >= 5.9.4 excluding 5.10.0, only for OpenSSL >= 1.0.2 (so that ALPN is available), only for https (unencrypted HTTP/2 may be corrupted by misbehaving proxy, if needed it can be enabled by client application)

**Comment by annulen** [comment] 2018-01-31 09:21
Bug https://bugreports.qt.io/browse/QTBUG-63722 means that only Qt >= 5.10.1 is ok for HTTP/2

**Comment by annulen** [comment] 2019-06-09 20:18
Fixed in 7c6c64d6ea744e2dc352a2eb11f9cb07318b05b5

**Closed by annulen** 2019-06-09 20:18 UTC
Labels: bug
