### ISSUE TITLE
build-webkit forces VS2017 build

### ISSUE THREAD

**Issue by izzyonstage** [annulen/webkit#545] opened 2017-05-17 11:55 UTC
I am currently trying to build a new version of QtWebKit with a static build of Qt-5.7.1

Even though I have started the VS2015 Command Prompt, when I run the following script cmake detects only VS2017.

`perl Tools/Scripts/build-webkit --qt --release --32-bit --only-webkit --no-ninja --no-device-orientation --no-web-audio --no-video --no-video-track --no-touch-events --no-touch-slider --no-geolocation --no-xslt --no-netscape-plugin-api --cmakeargs="-Wno-dev -DENABLE_PRINT_SUPPORT=OFF -DCMAKE_PREFIX_PATH=C:\Qt\Static\5.7.1\qtbase"`

Any ideas as to why this is?
If I am following the logs correctly it appears that cmake is compiling some code using VS2017 in order to detect the compiler version.

**Comment by annulen** [comment] 2017-05-17 12:03
First of all, --32-bit and --only-webkit have no effect for Qt port, and --no-ninja is not really needed because by default ninja won't be used if it is not present in PATH

>Any ideas as to why this is?

Check your PATH

**Comment by izzyonstage** [comment] 2017-05-17 12:16
My PATH is only configured with VS2015 due to being in the VS2015 Comand Prompt

> First of all, --32-bit and --only-webkit have no effect for Qt port, and --no-ninja is not really needed because by default ninja won't be used if it is not present in PATH

I will remove these now if they are irrelevant. I only put them in as belt-and-braces aproach to make sure it only built specifically what I need.

**Comment by annulen** [comment] 2017-05-17 12:18
Could you post what `PATH` command prints in your shell?

**Comment by izzyonstage** [comment] 2017-05-17 12:41
Sure, this is what I have before and after I run my build script.

Before Script:
[https://pastebin.com/wfqPqYYp](https://pastebin.com/wfqPqYYp)

After Running My Script:
[https://pastebin.com/79Y7NCJ3](https://pastebin.com/79Y7NCJ3)

**Comment by annulen** [comment] 2017-05-17 12:45
Could you post log of cmake?

**Comment by annulen** [comment] 2017-05-17 12:49
Also, if you run `cl` what version does it print?

**Comment by annulen** [comment] 2017-05-17 12:52
OK, don't bother. By default CMake looks in registry for newest VS version installed, and it doesn't give a damn about your PATH.

To work around, you need to specify generator with "-G" option of cmake, or use ninja. I can change default generator of build-webkit to nmake, if ninja is not found

**Comment by izzyonstage** [comment] 2017-05-17 13:02
If I specify the -G option it still seems to pick up the VS2017 compiler version details

What change would be required to force the nmake build if not ninja?

**Comment by annulen** [comment] 2017-05-17 13:27
-G needs generator name as an argument, e.g. `-G Nmake Makefiles` or `-G Visual Studio 14 2015`. See `cmake --help` and cmake's documentation for more details.

I just realized `Nmake Makefiles` would be a bad choice as it doesn't allow parallel build.  `Nmake Makefiles JOM` is what I had in mind, but it depends on presence of jom.

**Comment by izzyonstage** [comment] 2017-05-17 13:32
I have:
-G "Visual Studio 14 2015"
Maybe I need to remove the quotes?

**Comment by annulen** [comment] 2017-05-17 13:35
No it should use VS 2015. Could you show your log?

**Comment by izzyonstage** [comment] 2017-05-17 15:51
Have just had to launch a new build so will post this when I am back at my desk tomorrow morning UK time.

**Comment by bagong** [comment] 2017-05-20 20:14
I've had a similar symptom with VS2015. I properly asked `-G "Visual Studio 14 2015 Win64` and even was using VS2015 developer prompt - cmake returned C/CXX compiler not found. In my case the Windows 10 SDK was missing, or more precisely the right version. I only had the latest version, which only goes with VS2017. You need version 10.0.14393.795. The problem was: rc.exe missing. The error-message was in build-folder\CMakeFiles\CMakeError.log. Cmake tests for the availability of cl and rc and throws a unspecific error if rc fails to be found. The resource compiler (and debugger) are in the Windows SDK, but only an older SDK version goes with VS 2015.

**Comment by annulen** [comment] 2017-05-20 22:17
@Vitallium Have you experienced anything like this?

**Comment by Vitallium** [comment] 2017-05-21 09:31
@annulen I think I had the same problem.

Check that:
1) you have installed latest CMake version
2) you have installed SDK plus native build tools. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/1894248/26282817/50f19670-3e21-11e7-8414-9ebebacc2a40.png)
![image](https://cloud.githubusercontent.com/assets/1894248/26282820/5be01868-3e21-11e7-9969-f64bf975eb95.png)

**Comment by bagong** [comment] 2017-05-21 09:48
Just *if* we're all talking about the same problem: in order to build with VS2015 the `Windows 10 SDK (10.0.*14393*.0)` entry has to be ticked. One is tempted to go with "the latest only" (and save a few GB), but `Windows 10 SDK (10.0.15064.0)` cannot be used by VS2015. MS could be a bit clearer about that, the SDK download is a bit messy. This is the clearest I found (see the Note):

https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk

I wonder if VS2017 with that older SDK and the `VC++ 2015.3 vs140 toolset` installed is enough to do "VS2015" builds, or whether you still need VS2015 installed and VS2017 Installer is just kind of a meta installer that keeps track of VS2015 also? Being able to remove VS2015 would simplify system maintenance.

**Comment by izzyonstage** [comment] 2017-05-22 07:35
Not sure if that issue applies to me. I work mainly with VS2015. I have only installed VS2017 for a few small projects using .NetCore. Have been having other problems with my build system. will try to get a build log attached here at some point today.

**Comment by annulen** [comment] 2017-05-22 08:13
FWIW, it may make sense to do full switch to 2017, people say it's binary compatible with 2015.

**Comment by bagong** [comment] 2017-05-22 08:35
If you start fresh that's likely good. Looks like they are trying hard to push people to VS2017 with attractive features and provide backwards compatibility with VS2015. But if you have a running VS2015 system with scripts, you might want to think twice. I found that my old builds don't work anymore if I just use VS2017 and enable all the VS2015 related addons, paths have changed. Also to identify the right SDK is not trivial. I am not even sure if what I said above is right. The complicating factor is that "MS universal builds" are another story again. I ended up reinstalling 2015 for now ;) But going fully 2017 is likely cleaner on the long run. Fortunately VS2015, VS2017 and even VS 2013 coexist peacefully on the same system.

**Comment by izzyonstage** [comment] 2017-05-22 16:49
Currently I am not allowed to just move everything over to VS2017. I have many other projects that for contractual reasons have to be in VS2015. Latest run with the -G flag specified ends up not creating the required cmake files. the output directory is created but nothing is put in it. If I don't use the -G parameter then it tries to use VS2017 and then errors about something to do with linking (I assume this is because the Qt static libs were built with VS2015 not VS2017).

**Comment by annulen** [comment] 2017-05-22 16:55
>Latest run with the -G flag specified ends up not creating the required cmake files. the output directory is created but nothing is put in it

This indicates some serious error that must be clearly visible in log. At least it should have been creating compiler tests in build dir.

**Comment by izzyonstage** [comment] 2017-05-22 16:57
only thing in there is build-webkit-options.txt

**Comment by annulen** [comment] 2017-05-22 16:58
I need your exact command line and output

**Comment by izzyonstage** [comment] 2017-05-22 17:00
> I need your exact command line and output

```
The qtwebkit-libs-win has been sucessfully installed in
 C:\Qt\Static\qtwebkit\WebKitLibraries\win
Not searching for unused variables given on the command line.
CMake Error: The source directory "C:/Qt/Static/qtwebkit-bin/Release" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
```

**Comment by annulen** [comment] 2017-05-22 17:02
What command are you running exactly?

**Comment by izzyonstage** [comment] 2017-05-22 17:06
have updated previous post. accidentally hit comment before I had copied it all across

**Comment by annulen** [comment] 2017-05-22 17:26
What if you try

   perl Tools/Scripts/build-webkit --qt --release --no-device-orientation --no-netscape-plugin-api --no-web-audio --no-geolocation --no-xslt --no-video --no-video-track --no-touch-events --no-touch-slider --cmakeargs="-Wno-dev -DENABLE_PRINT_SUPPORT=OFF -DCMAKE_PREFIX_PATH=\"C:\Qt\Static\5.7.1\" -G \"Visual Studio 14 2015\""

**Comment by annulen** [comment] 2017-05-22 17:30
updated previous post, github have eaten escapes

**Comment by bagong** [comment] 2017-05-22 17:57
It's hungry ;)

**Comment by izzyonstage** [comment] 2017-05-22 18:04
Not sure how that is different from what I am currently running. except for the missing escaping quotes.

**Comment by annulen** [comment] 2017-05-22 18:12
Then switch to manual cmake invocation. build-webkit does nothing more than 1) run update-qtwebkit-win-libs; 2) detect if ninja is available; 3) run cmake, by default in WebKitBuild/Release

You'll need to convert command line switches to cmake variable names, e.g. --no-device-orientation  => -DENABLE_DEVICE_ORIENTATION=OFF. See Source/cmake/WebKitFeatures.cmake for full list

**Comment by bagong** [comment] 2017-05-22 18:22
But @izzyonstage , this latest command posted by @annulen does work for me. On a system where VS 2013, 2015 and 2017 are installed, VS2015 is identified correctly...

PS: is this a insource build? I am not going to mess up my repo, am I?

**Comment by annulen** [comment] 2017-05-22 18:23
build-webkit cannot do in-source builds :)

**Comment by izzyonstage** [comment] 2017-05-23 08:15
> in-source builds
what is meant by this?

I essentially have a clone of git repo and am running the perl command from the root directory of the local repo.

Have amended the double quotes and it does seem to get further now. I am still getting errors though about WebKit PDB. Just running a new build now so will post the details shortly.

**Comment by izzyonstage** [comment] 2017-05-23 08:32
error is:
> CMake Error:
>   Error evaluating generator expression:
>     $<TARGET_PDB_FILE:WebKitWidgets>
>   TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
[CMakeError.log.txt](https://github.com/annulen/webkit/files/1021415/CMakeError.log.txt)

**Comment by annulen** [comment] 2017-05-23 08:49
I'm leaning towards declaring "Visual Studio" generators as unsupported and "use at your own risk"

**Comment by annulen** [comment] 2017-05-23 08:57
The only generator for MSVC that is checked in CI is "Nmake Makefiles JOM", while "Ninja" and "Nmake Makefiles" should work because they are quite similar. I don't have time to debug anything else.

**Comment by bagong** [comment] 2017-05-23 08:59
But Visual Studio is extremely popular among Windows developers. And with the ninja build I get problems too (and I've seen that in other projects too, ninja seems to be more brittle). It's fine if it works, of course (vcpkg prefers ninja too)... Isn't msbuild required to debug with Visual Studio?

**Comment by annulen** [comment] 2017-05-23 09:02
I only know that post-mortem debugger does not require any project

**Comment by bagong** [comment] 2017-05-23 09:06
@izzyonstage , could it be that you are using an old cmake version? You get quite a few errors I don't see, and I wonder what would be different between our environments. I am using cmake 3.8.1. Windows compatibility and e.g. generator expressions support has developed in the more recent cmake versions.

**Comment by izzyonstage** [comment] 2017-05-23 09:09
I am using 3.8.0 of cmake

**Comment by bagong** [comment] 2017-05-23 09:10
Ah well, that's close enough...

**Comment by izzyonstage** [comment] 2017-05-23 09:12
it was previously working, however I have had to rebuild Qt as a static lib as I need to use this for my internal version of PhantomJS. that is the only difference from what I ran before that did seem to work.
Just pointing it to the static version I built locally (which was built with nmake if I remember correctly).

**Comment by izzyonstage** [comment] 2017-05-23 09:13
is it possible to build QtWebKit with nmake?

**Comment by bagong** [comment] 2017-05-23 09:21
If Annulen want's people to use ninja, we could try to get through and hope for his help ;)

**Comment by izzyonstage** [comment] 2017-05-23 09:24
I can't use ninja. My build system does not have it on and I don't have access or privileges to install it.

**Comment by bagong** [comment] 2017-05-23 09:28
Ah, well, - just in case - you are wondering how to make the system use nmake. The way according to the books would be to use a visual studio 2015 developer prompt (which will make cmake find the correct compiler) and then specify `-G "NMake Makefiles" instead of the reference to VS in the -G term.

**Comment by annulen** [comment] 2017-05-23 10:04
Qt is normally built with jom on Windows

**Comment by annulen** [comment] 2017-05-23 10:08
>My build system does not have it on and I don't have access or privileges to install it.

If you are able to run gnuwin32 tools, you can run ninja in the smae manner by putting it to the same directory, or any othger directory where you can write and add it to %PATH%

**Comment by izzyonstage** [comment] 2017-05-23 14:54
Ok, I have just rebuilt Qt specifically using JOM.
I have re-run the build for QtWebKit using:
`-G "NMake Makefiles JOM"`
But I am still getting:
```
CMake Error:
  Error evaluating generator expression:
    $<TARGET_PDB_FILE:WebKitWidgets>
  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.

CMake Error:
  Error evaluating generator expression:
    $<TARGET_PDB_FILE:WebKit>
  TARGET_PDB_FILE is allowed only for targets with linker created artifacts.
```
Any ideas?

**Comment by bagong** [comment] 2017-05-23 15:10
No, sorry. Can't understand it.
https://gitlab.kitware.com/cmake/cmake/commit/f86850ef60b7dc008a144722bd0c803289a8ab76

You're building debug mode, right... I'll try that next after my release mode ninja build succeeded.

**Comment by annulen** [comment] 2017-05-23 16:11
@izzyonstage 

Quick workaround is to comment lines with `$<TARGET_PDB_FILE:...` in Source/WebKit/CMakeLists.txt and  Source/WebKit/PlatformQt.cmake

@bagong
>generator expressions support has developed in the more recent cmake versions

FWIW, I'm using only cmake features that are present in 2.8.12

**Comment by izzyonstage** [comment] 2017-05-23 17:01
@bagong no I am building the release version

I was thinking about removing cmake and putting 2.8 version on instead to see what happens.

**Comment by bagong** [comment] 2017-05-23 18:08
@izzyonstage , so it's different now, right? That old error-log seemed to say your build configuration was debug. Did you add`-DCMAKE_BUILD_TYPE=Release` in your cmake-arguments? I wonder how one would set build configuration in that perl build.

**Comment by izzyonstage** [comment] 2017-05-23 18:28
when calling the perl script there is a command line argument "--release" that should set it to be release build.

**Comment by annulen** [comment] 2017-05-23 18:29
Release mode is default

**Comment by izzyonstage** [comment] 2017-05-23 18:29
Might have to debug the perl script myself and just call cmake directly.

**Comment by bagong** [comment] 2017-05-23 18:36
The error log you posted above starts:

````
Determining if files features.h exist failed with the following output:
Change Dir: C:/Qt/Static/qtwebkit-bin/Release/CMakeFiles/CMakeTmp

Run Build Command:"C:/Program Files (x86)/MSBuild/14.0/bin/MSBuild.exe" "cmTC_1ba3c.vcxproj" "/p:Configuration=Debug" "/p:VisualStudioVersion=14.0"
Microsoft (R) Build Engine version 14.0.25420.1

Copyright (C) Microsoft Corporation. All rights reserved.
````

But now you're not msbuild anymore, so it might in fact be different...

**Comment by izzyonstage** [comment] 2017-05-24 09:05
I am using JOM now, but under the hood does that not just call pretty much the same stuff as MSBuild does?

Still failing with same errors.
Have just added the removal of those lines in my build script so will see if that fixes things.

**Comment by izzyonstage** [comment] 2017-05-24 09:19
Still no go I'm afraid.

It does get further, but now errors with:
```
[  6%] Linking CXX static library ..\..\lib32\ANGLESupport.lib
jom: C:\Qt\Static\qtwebkit\WebKitBuild\Release\CMakeFiles\Makefile2 [Tools\ImageDiff\CMakeFiles\ImageDiff.dir\all] Error 2
jom: C:\Qt\Static\qtwebkit\WebKitBuild\Release\Makefile [all] Error 2
```

**Comment by annulen** [comment] 2017-05-24 09:24
Please post actual error messages if you want to get help

**Comment by izzyonstage** [comment] 2017-05-24 09:45
sorry, that was all I saw after the script ran.
just dumped output to file and this is what it has:

[https://pastebin.com/g8XFfSaB](https://pastebin.com/g8XFfSaB)

**Comment by annulen** [comment] 2017-05-24 09:47
Actual errors are

    error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MD_DynamicRelease' in ImageDiff.cpp.obj

etc. Well, there is runtime mixing somewhere

**Comment by izzyonstage** [comment] 2017-05-24 11:37
any idea why ImageDiff is not built as static?
This would appear to be part of the webkit repository so unsure how to fix this.

**Comment by annulen** [comment] 2017-05-24 11:38
I would expect all binaries to use shared runtime, i.e. MD or MDd

**Comment by izzyonstage** [comment] 2017-05-24 11:47
in which case it is probably not going to work with my static Qt build which is both -static and -static-runtime. will change that and see what happens then.

**Comment by annulen** [comment] 2017-05-24 11:48
Well, maybe it's possible to make it working with MT. How are you setting respective flags to QtWebKit?

**Comment by izzyonstage** [comment] 2017-05-24 13:53
currently I am running this:

`perl Tools/Scripts/build-webkit --qt --release --cmakeargs="-Wno-dev -DCMAKE_BUILD_TYPE=Release -DENABLE_DEVICE_ORIENTATION=OFF -DENABLE_GEOLOCATION=OFF -DENABLE_TOUCH_SLIDER=OFF -DENABLE_TOUCH_EVENTS=OFF -DENABLE_VIDEO=OFF -DENABLE_VIDEO_TRACK=OFF -DENABLE_WEB_AUDIO=OFF -DENABLE_XSLT=OFF -DENABLE_NETSCAPE_PLUGIN_API=OFF -DENABLE_PRINT_SUPPORT=OFF -DCMAKE_PREFIX_PATH=\"C:/Qt/Static/5.7.1\" -G \"NMake Makefiles JOM\""`

**Comment by annulen** [comment] 2017-05-24 14:03
Add -DUSE_STATIC_RUNTIME=ON

Sorry, I forgot that we have this option

**Comment by annulen** [comment] 2017-05-24 14:08
BTW, you can see all available options by using cmake-gui or ccmake, or by looking at Source/cmake/OptionsQt.cmake, OptionsCommon.cmake, WebKitFeatures.cmake

**Comment by izzyonstage** [comment] 2017-05-24 17:09
I no longer see the Static errors, but undefined methods.
[https://pastebin.com/VSrH3wpv](https://pastebin.com/VSrH3wpv)

**Comment by annulen** [comment] 2017-05-24 17:52
Is libGLESv2.lib coming from Qt?

**Comment by izzyonstage** [comment] 2017-05-24 18:58
it should be. it is in C:\Qt\Static\5.7.1\lib.

**Comment by izzyonstage** [comment] 2017-05-25 15:29
just an FYI for this thread.

I have rebuilt Static Qt and used the "-no-angle -opengl desktop" options which seems to have removed the build of the lib that caused the previous failure. Currently rebuilding QtWebKit but it seems to hang at 8% after the "Built target TestWTF".

Any idea what is supposed to be happening at this point?

**Comment by annulen** [comment] 2017-05-25 15:32
check list of active processes. If cmake.exe is in top, just wait a little more

**Comment by annulen** [comment] 2017-05-25 15:36
BTW, if you are disabling opengl in Qt, you should also set -DENABLE_OPENGL=OFF when building qtwebkit

**Comment by izzyonstage** [comment] 2017-05-25 15:38
There is still a Qt5OpenGL.lib built, it just does not use the ANGLE stuff to mapp to DirectX. At least that is how I read it and it now seems to be working. Am at 22% with QtWebKit build now. Furthest I got before was 9%.

**Comment by izzyonstage** [comment] 2017-05-25 15:41
Just wondering, does the build script do a "nmake install" call or is that something I will have to do myself after the build to export all the required files into my Qt directory (and module info directories)? As will need this so I can build PhantomJS with the built binaries.

**Comment by annulen** [comment] 2017-05-25 15:41
Qt5OpenGL is not what ENABLE_OPENGL=OFF is about, the latter disables Opengl-based accelerated compositing and WebGL, which don't use Qt5OpenGL but require working gl stuff

**Comment by annulen** [comment] 2017-05-25 15:42
Currently you need to run nmake/jom install manually, however I can add --install to build-webkit

**Comment by izzyonstage** [comment] 2017-05-25 15:45
OK, I have added that to my script for the OpenGL stuff.
A "--install" option would be great if possible.

**Comment by izzyonstage** [comment] 2017-05-25 16:16
another error during build at 29-30%:
```
[ 30%] Linking CXX executable ..\..\..\bin32\jsc.exe
sicuuc.lib(uenum.ao) : error LNK2005: _uenum_close_57 already defined in icuuc.lib(icuuc57.dll)
sicuuc.lib(uenum.ao) : error LNK2005: _uenum_next_57 already defined in icuuc.lib(icuuc57.dll)
sicuuc.lib(uenum.ao) : error LNK2005: _uenum_unext_57 already defined in icuuc.lib(icuuc57.dll)
sicuuc.lib(uloc.ao) : error LNK2005: _uloc_getDefault_57 already defined in icuuc.lib(icuuc57.dll)
   Creating library ..\..\..\lib32\jsc.lib and object ..\..\..\lib32\jsc.exp
..\..\..\bin32\jsc.exe : fatal error LNK1169: one or more multiply defined symbols found
LINK failed. with 1169
jom: C:\Qt\Static\qtwebkit\WebKitBuild\Release\Source\JavaScriptCore\shell\CMakeFiles\jsc.dir\build.make [bin32\jsc.exe] Error 2
jom: C:\Qt\Static\qtwebkit\WebKitBuild\Release\CMakeFiles\Makefile2 [Source\JavaScriptCore\shell\CMakeFiles\jsc.dir\all] Error 2
[ 29%] Generating ../../DerivedSources/WebCore/WebKitVersion.h
```
I assume this is to do with icu linking? Qt is build against static icu, but this seems to be trying to link to dynamic lib (if I have read it correctly)?

**Comment by izzyonstage** [comment] 2017-05-26 10:58
anyone know how to fix the above issue with linking against the static icu library?

**Comment by annulen** [comment] 2017-05-26 11:04
Zip file with precompiled dependencies includes ICU built as dlls, and cmake uses this libraries by default. You should remove them and replace with your static ICU.

**Comment by izzyonstage** [comment] 2017-05-26 12:10
is that for the webkit-libs-win.zip? if so, is there a way to skip that step in the script? as I already have all the required dependencies which I copy into the relevant folders. I guess that the build-webkit script is just overwriting what I have already copied in there.

**Comment by annulen** [comment] 2017-05-26 12:15
Don't use build-webkit, in your conditions it makes no sense

**Comment by izzyonstage** [comment] 2017-06-05 15:58
I have reverted to calling cmake directly now.

> Zip file with precompiled dependencies includes ICU built as dlls, and cmake uses this libraries by default. You should remove them and replace with your static ICU
This I have done, the problem seems to be that FindICU only searches for icuuc and not the static version sicuuc.

**Comment by bagong** [comment] 2017-06-05 16:13
Oh wow, that's an unusual naming convention. Good to know!

**Comment by izzyonstage** [comment] 2017-06-06 09:10
@bagong that is strange. I am using the built dependencies from the Qt build repo.
I am also confuse on why OptionsWin.cmake is setting ICU_LIBRARIES to libicu**.lib?
Also is there an option for CMAKE that I can check for requested static compilation? (I know there is one for the static runtime linking, but cant find one for 3rd party library static linking).

**Comment by bagong** [comment] 2017-06-06 10:50
Sorry, I can only contribute some half-knowledge or speculation. 

The general logic of cmake is to link statically if it *finds* static libraries and dynamically in the other case. What it finds is determined by the path it looks in (order!) and the names of files it looks for (an extension in the name can make a big difference ;) ). CRT linkage is in fact a different story, as it can be controlled via compiler option. Setting a build to static per "cmake command" independently of given find-paths and names is not possible to my knowledge, except it has been implemented in the build-scripts. Cmake does not offer a static/dynamic switch as it does for debug/release.

`ICU_LIBRARIES to libicu**.lib`looks like looking for multiple libs at once, which makes sense in a cmake logic, where a library variable can take multiple values. That it gives the lib-prefix makes me think it uses mingw-naming convention, which is not what you'd want (and cmake will actually add lib by itself in a mingw-context, so that actually looks wrong to me). I didn't know you could use wild-cards. I think what you need to do is check in the respective CMakeCache.txt if things are found as expected in your particular environment and adjust the FindModule if not. But usually people use cmake-gui, enter wrong paths manually and then make sure that their CMakeCache.txt doesn't get lost ;)

**Comment by izzyonstage** [comment] 2017-06-06 11:08
Think I have a solution:
Change Source/cmake/OptionsQt.cmake
from:
```
if (NOT QT_CONAN_DIR)
    set(ICU_LIBRARIES icuuc${CMAKE_DEBUG_POSTFIX} icuin${CMAKE_DEBUG_POSTFIX} icudt${CMAKE_DEBUG_POSTFIX})
endif ()
```
to:
```
if (NOT QT_CONAN_DIR)
    if (QT_STATIC_BUILD OR ICU_STATIC)
        set(ICU_LIBRARIES sicuuc${CMAKE_DEBUG_POSTFIX} sicuin${CMAKE_DEBUG_POSTFIX} sicudt${CMAKE_DEBUG_POSTFIX})
    else ()
        set(ICU_LIBRARIES icuuc${CMAKE_DEBUG_POSTFIX} icuin${CMAKE_DEBUG_POSTFIX} icudt${CMAKE_DEBUG_POSTFIX})
    endif ()
endif ()
```
around line 750. bottom of the "if (MSVC)" block.

With this change I have now got to 90% build. Was previously failing at 29-30%.

**Comment by izzyonstage** [comment] 2017-06-06 11:18
Darn:
Failed at 95% Linking TestWebCore.

> [ 95%] Linking CXX executable ..\..\bin32\TestWebCore.exe
> libpng.lib(pngread.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
>    Creating library ..\..\lib32\TestWebCore.lib and object ..\..\lib32\TestWebCore.exp
> LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
> libeay32.lib(ui_openssl.obj) : error LNK2001: unresolved external symbol ___iob_func
> libeay32.lib(pem_lib.obj) : error LNK2001: unresolved external symbol ___iob_func
> libeay32.lib(txt_db.obj) : error LNK2001: unresolved external symbol ___iob_func
> libeay32.lib(e_capi.obj) : error LNK2001: unresolved external symbol ___iob_func
> libeay32.lib(gost_eng.obj) : error LNK2001: unresolved external symbol ___iob_func
> ssleay32.lib(s3_srvr.obj) : error LNK2001: unresolved external symbol ___iob_func
> ssleay32.lib(t1_enc.obj) : error LNK2001: unresolved external symbol ___iob_func
> ssleay32.lib(d1_both.obj) : error LNK2001: unresolved external symbol ___iob_func
> libeay32.lib(cryptlib.obj) : error LNK2001: unresolved external symbol ___iob_func
> MSVCRT.lib(_chandler4gs_.obj) : error LNK2001: unresolved external symbol __except_handler4_common
> ..\..\bin32\TestWebCore.exe : fatal error LNK1120: 2 unresolved externals
> LINK failed. with 1120

**Comment by izzyonstage** [comment] 2017-06-06 11:35
need to figure out how to add "legacy_stdio_definitions.lib" include for _MSC_VER >= 1900

**Comment by annulen** [comment] 2017-06-06 11:41
Are you able to build just WebKitWidgets target?

**Comment by izzyonstage** [comment] 2017-06-06 14:50
How do I turn off building the Tests?

**Comment by izzyonstage** [comment] 2017-06-06 14:52
Just wondering if I can avoid this in my case by using dynamic runtime and not the static runtime options?

**Comment by annulen** [comment] 2017-06-06 15:29
I guess error you are getting may be caused by mismatching runtimes

How do I turn off building the Tests? - `-DENABLE_API_TESTS=OFF`. But you can just run something like `nmake WebKitWidgets` and skip building some targets

**Comment by izzyonstage** [comment] 2017-06-06 16:18
Is there a way to stop QtTestBrowser from building as I have the same issue with that?
last thing now as it is 100% point his causes an error.

It also seems to have errors with libpng and qtpng defining the same items.
Have added the following in OptionsQt.cmake to try and fix this in the bit that detects the QT_CORE_TYPE on line 260.
```
if (MSVC)
    set(QT_BUNDLED_JPEG ON)
    set(QT_BUNDLED_PNG ON)
    set(QT_BUNDLED_ZLIB ON)
endif ()
```

**Comment by annulen** [comment] 2017-06-06 16:21
Build WebKitWidgets target, e.g. `jom WebKitWidgets`

You need to disable png in Qt to avoid conflicts, as https://github.com/annulen/webkit/wiki/Building-static-libraries says

**Comment by izzyonstage** [comment] 2017-06-09 08:10
>Build WebKitWidgets target, e.g. jom WebKitWidgets
This does work, but when I do jom install it still fails trying to build QtTestBrowser
Looks like it is trying to build with /MD instead of /MT like everything else.

I have just made another small change to my build script and am re-running to see if it makes any difference with this.

**Comment by izzyonstage** [comment] 2017-06-09 11:43
it would seem that QtTestBrowser and DumpRenderTree are part of the installation definition.
However they fail to build in my windows build due to them not being linked to the static runtime (AFAICT).

**Comment by annulen** [comment] 2017-06-09 12:08
Indeed, install target depends on "all"

>Looks like it is trying to build with /MD instead of /MT like everything else.

This should not be the case. The only special thing that QtTestBrowser does is enabling WIN32_EXECUTABLE property, DumpRenderTree doesn't do even this.

Check how your dependencies are built.

**Comment by izzyonstage** [comment] 2017-06-09 12:28
which dependencies?
As far as I know everything lib-wise is built now with VS2015 statically with /MT.
But building QtTestBrowser seems to specify the none-static CRT libraries.

I have also noticed when removing the libpng stuff from Qt that when the build gets to QtTestBrower it errors with undefined symbol with libpng.

**Comment by annulen** [comment] 2017-06-09 12:51
>But building QtTestBrowser seems to specify the none-static CRT libraries.

Could you show linker command line arguments to proove this?

**Comment by izzyonstage** [comment] 2017-06-12 11:26
no, because the only thing that gets output is the 100% process and "linking QtTestBrowser" followed by linker messages about MD vs MT linkage. Is there a log somewhere that shows these linker commands?

**Comment by annulen** [comment] 2017-06-12 11:34
jom VERBOSE=1

**Closed** 2017-06-26 16:28 UTC
